apiVersion: v1
kind: Service
metadata:
  name: mc-vanilla
spec:
  type: NodePort
  ports:
  - port: 25565
    nodePort: 30001
  selector:
    app: mc-vanilla
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mc-vanilla
spec:
  selector:
    matchLabels:
      app: mc-vanilla
  template:
    metadata:
      labels:
        app: mc-vanilla
    spec:
      containers:
      - image: itzg/minecraft-server
        name: mc-vanilla
        env:
        - name: EULA
          value: "TRUE"
        ports:
        - containerPort: 25565
          name: main
        volumeMounts:
        - name: mc-vanilla
          mountPath: /data
      volumes:
        - name: mc-vanilla
          persistentVolumeClaim:
            claimName: minecraft-pv-claim
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: minecraft-pv-volume
  labels:
    type: local
    app: mc-vanilla
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data" #this should be a shared directory all nodes can reach
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-pv-claim
  labels:
    app: mc-vanilla
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
