apiVersion: app/v1
kind: Deployment
metadata:
  name: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-bedrock-server
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 25565
          env:
            - name: EULA
              value: "TRUE"
          envFrom:
            - configMapRef:
                name: minecraft-config
          volumeMounts:
            - mountPath: /var/lib/minecraft/data
              name: minecraft
      volumes:
        - name: minecraft
          persistentVolumeClaim:
            claimName: minecraft-pv-claim
